export type ZoneCategory = 'interior' | 'exterior';

export interface Zone {
  id: string;
  icon: string;
  name: string;
  category: ZoneCategory;
  categoryLabel: string;
  tasks: string[];
  photoHint: string;
  minPhotos: number;
  recommendVideo: boolean;
  estimatedMinutes: number;
  difficulty: number; // 1-5
  manualVideoUrl?: string;
}

export const ZONES: Zone[] = [
  {
    id: 'living',
    icon: '🏠',
    name: '거실',
    category: 'interior',
    categoryLabel: '내부',
    photoHint: '거실 전경, TV 화면, 전자레인지 내부, 바닥 상태',
    minPhotos: 3,
    recommendVideo: false,
    estimatedMinutes: 45,
    difficulty: 4,
    tasks: [
      '100인치 TV 화면+프레임 먼지 제거 (물티슈 사용, 세제 금지)',
      '전자레인지 4대: 내부 닦기 + 회전판 세척 + 문 안팎 닦기',
      '정수기: 배수트레이 비우기 + 출수구 주변 닦기',
      '개별 난방기: 먼지 제거 + 정상 작동 확인',
      '쿠션/매트: 배치 정리 + 얼룩 확인 (심하면 세탁 or 교체)',
      '화이트보드: 지우개로 말끔히 지우기 + 마커 상태 확인',
      '보드게임/놀이도구: 구성품 확인 + 정리 정돈',
      '바닥: 쓸기 → 물걸레 (으깨진 음식물 처리 필수)',
      '콘센트/스위치 닦기',
      '전체 창문 개방 환기 (최소 15분)',
    ],
  },
  {
    id: 'small_room_left',
    icon: '🛏️',
    name: '좌측 작은방1',
    category: 'interior',
    categoryLabel: '내부',
    photoHint: '방 전경, 침구 상태, 바닥',
    minPhotos: 2,
    recommendVideo: false,
    estimatedMinutes: 18,
    difficulty: 2,
    tasks: [
      '침구: 사용한 이불/베개커버 수거 → 새 침구 세팅',
      '바닥: 쓰레기 수거 → 쓸기 → 물걸레',
      '창문 개방 환기 (최소 15분)',
      'TV/리모컨 닦기 (있는 경우)',
      '히터/에어컨: 작동 확인 + 주변 먼지 제거',
      '콘센트/조명 점검 + 닦기',
      '문잠금 정상 작동 확인',
    ],
  },
  {
    id: 'small_room_right',
    icon: '🛏️',
    name: '우측 작은방2',
    category: 'interior',
    categoryLabel: '내부',
    photoHint: '방 전경, 침구 상태, 바닥',
    minPhotos: 2,
    recommendVideo: false,
    estimatedMinutes: 18,
    difficulty: 2,
    tasks: [
      '침구: 사용한 이불/베개커버 수거 → 새 침구 세팅',
      '바닥: 쓰레기 수거 → 쓸기 → 물걸레',
      '창문 개방 환기 (최소 15분)',
      'TV/리모컨 닦기 (있는 경우)',
      '히터/에어컨: 작동 확인 + 주변 먼지 제거',
      '콘센트/조명 점검 + 닦기',
      '문잠금 정상 작동 확인',
    ],
  },
  {
    id: 'big_room_1',
    icon: '🛌',
    name: '큰방1',
    category: 'interior',
    categoryLabel: '내부',
    photoHint: '방 전경, 침구, 바닥, 히터 상태',
    minPhotos: 2,
    recommendVideo: false,
    estimatedMinutes: 23,
    difficulty: 3,
    tasks: [
      '���구: 사용한 이불/베개커버 전체 수거 → 새 침구 세팅',
      '바닥: 쓰레기 수거 → 쓸기 → 물걸레',
      '창문 개방 ��기 (최소 15분)',
      'TV 화면 + 리��컨 닦기',
      '히터/��어컨: 작동 확인 + 먼지 제거',
      '콘센트/조명 점검 + 닦기',
      '문잠금 정상 작동 확인',
      '이불장/수납공간 정리 확인',
    ],
  },
  {
    id: 'big_room_2',
    icon: '🛌',
    name: '큰방2',
    category: 'interior',
    categoryLabel: '내부',
    photoHint: '방 전경, 침구, 바닥, 히터 상태',
    minPhotos: 2,
    recommendVideo: false,
    estimatedMinutes: 23,
    difficulty: 3,
    tasks: [
      '침구: 사용한 이불/베개커버 전체 수거 → 새 침구 세팅',
      '바닥: 쓰레기 수거 → 쓸기 → 물걸레',
      '창문 개방 환기 (최소 15분)',
      'TV 화면 + 리모컨 닦기',
      '히터/에어컨: 작동 확인 + 먼지 제거',
      '콘센트/조명 점검 + 닦기',
      '문잠금 정상 작동 확인',
      '이불장/수납공간 정리 확인',
    ],
  },
  {
    id: 'bathroom_female',
    icon: '🚺',
    name: '여자화장실',
    category: 'interior',
    categoryLabel: '내부',
    photoHint: '변기, 세면대/거울, 샤워부스, 소모품 보충 상태',
    minPhotos: 3,
    recommendVideo: false,
    estimatedMinutes: 23,
    difficulty: 4,
    tasks: [
      '변기: 내부/외부 세척 + 좌석 뒤쪽까지',
      '세면대: 물때 제거 + 거울 닦기 + 배수구 청소',
      '샤워���스: 물때 제거제 사용 + 바닥/벽면 세척',
      '바닥: 배수구 머리카락 제거 + 세척 + 물기 제거',
      '화장지 보충 (2롤 이상)',
      '핸드솔/비누 보충',
      '환풍기 정상 작동 확인',
      '휴지통 비우기 + 봉투 교체',
    ],
  },
  {
    id: 'bathroom_male',
    icon: '🚹',
    name: '���자화장실',
    category: 'interior',
    categoryLabel: '내부',
    photoHint: '변기, 세면대/거울, 샤워부스, 소모품 보충 상태',
    minPhotos: 3,
    recommendVideo: false,
    estimatedMinutes: 23,
    difficulty: 4,
    tasks: [
      '변기: 내부/외부 세척 + 좌석 뒤쪽까지',
      '세면대: 물때 제거 + 거울 닦기 + 배수구 청소',
      '샤워부스: 물때 제거제 사용 + 바닥/벽면 세척',
      '바닥: 배수구 머리카락 제거 + 세척 + 물기 제거',
      '화장�� 보충 (2롤 이상)',
      '핸드솔/비누 보충',
      '환풍기 정상 작동 확인',
      '휴지통 비우기 + 봉투 교체',
    ],
  },
  {
    id: 'kitchen',
    icon: '🍳',
    name: '부엌',
    category: 'interior',
    categoryLabel: '내부',
    photoHint: '싱크대, 조리대, 식탁, 냉장고 내부, 바닥',
    minPhotos: 3,
    recommendVideo: false,
    estimatedMinutes: 35,
    difficulty: 4,
    tasks: [
      '싱크대: 음식물 수거 → 세척 → 배수구 냄새 확인',
      '조리대: 기름때 제거 → 세제 세척 → 마른 헝겊 마무리',
      '가스렌지: 버너 분리 세척 + 불판 기름 제거',
      '식탁: 대형 식탁 전체 닦기 + 의자 ���리',
      '타일 바닥: 쓸기 ��� 물걸레 (음식물 흔적 집중)',
      '수저/조리도구: 세척 후 제자리 보관',
      '냉장고: 내부 잔여물 제거 + 닦기',
      '쓰레기봉투 교체 (분리수거 확인)',
    ],
  },
  {
    id: 'storage',
    icon: '🗄️',
    name: '창고',
    category: 'interior',
    categoryLabel: '내부',
    photoHint: '창고 내부 전경, 소모품 재고 상태',
    minPhotos: 1,
    recommendVideo: false,
    estimatedMinutes: 10,
    difficulty: 1,
    tasks: [
      '청소도구 제자리 보관 확인',
      '소모품 재고 확인 (화장지, 비누, 세제 등)',
      '바닥 쓸기',
      '정리 정돈 상태 확인',
      '부족 소모품 목록 작성 (메모)',
    ],
  },
  {
    id: 'bbq',
    icon: '🔥',
    name: '바베큐 시설',
    category: 'exterior',
    categoryLabel: '외부',
    photoHint: '그릴 상태, 테이블, 야외 전경, 마당',
    minPhotos: 3,
    recommendVideo: true,
    estimatedMinutes: 35,
    difficulty: 5,
    tasks: [
      '그릴: 잔여 음식�� 제거 → 철수세미 세척 → 건조 (최대 6개)',
      '숯불/재: 완전 소화 확인 → 재 수거 → 사용 가능한 숯 보충',
      '토치: 작동 확인 + 가스 잔량 체크',
      '야외 테이블: 음식물/흔적 제거 → 닦기',
      '야외 바닥: 쓸기 + 물청소 (기름때 주의)',
      '마당 쓰레기 수거 + 화단 정리',
      '야외 조명 정상 작동 확인',
      '야외 수도꼭지/호스 정리',
    ],
  },
];

export const INTERIOR_ZONES = ZONES.filter(z => z.category === 'interior');
export const EXTERIOR_ZONES = ZONES.filter(z => z.category === 'exterior');
export const TOTAL_TASKS = ZONES.reduce((sum, z) => sum + z.tasks.length, 0);
export const TOTAL_MIN_PHOTOS = ZONES.reduce((sum, z) => sum + z.minPhotos, 0);
